<meta charset="utf-8">
<style>
div#container{
	position:absolute;
	width: 100%;
	height: 100%;
	top: 0px;
	left:0px;
	background-color: #eee;
	display: block;
}
div#loader{
	position: fixed;
	width: 100%;
	height: 100%;
	top: 0px;
	left:0px;
	background-color: #eee;
	background-image: url('/img/load.gif');
	background-position: center center;
	background-repeat: no-repeat;
	background-size: cover;
}

    
</style>




<div id="container">
		<div id="loader"></div>
		<div id="content">
			<img src="/img/4k.jpg" width="100%" height="auto"/>
			<img src="/img/4k.jpg" width="100%" height="auto"/>
			<img src="/img/4k.jpg" width="100%" height="auto"/>
			<img src="/img/4k.jpg" width="100%" height="auto"/>
			<img src="/img/4k.jpg" width="100%" height="auto"/>
			<img src="/img/4k.jpg" width="100%" height="auto"/>
			<img src="/img/4k.jpg" width="100%" height="auto"/>
			<img src="/img/4k.jpg" width="100%" height="auto"/>
		</div>
	</div>
	<script type="text/javascript">
		// Este evendo é acionado após o carregamento da página
		 $(document).ready(function () {
			//Após a leitura da pagina o evento fadeOut do loader é acionado, esta com delay para ser perceptivo em ambiente fora do servidor.
			jQuery("#loader").delay(2000).fadeOut("slow");
		});
	</script>