
<meta charset="utf-8">



<script type="text/javascript">
    $(document).ready(function () {
        $('table tr#destaque').click(function () {
            window.location = $(this).data('url');
            returnfalse;
        });

    });


</script>

<style rel="stylesheet" type="text/css">

    .formbusca { float: left;  }
    .busca { margin-left: 0; margin-top: 60px;}
    table#listar tr#destaque{
        font-size: 13px; color: darklategray;
    }
    table#listar tr#destaque:nth-child(2n) {
        background:#dff0d8;
        margin-bottom: 5px;

    }
    .title_tabela {
        background-color: white;

    }
    
     
</style>

 

    
<div  class="container">

    <table  class="formbusca"> 
        <?php if (!@count($this->listaPacientes)) { ?>
        <tr>
            <td>
                <legend><font  color="gray">Busca de Paciente</font></legend>

                <a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'listar'), null, true) ?>">Listar Paciente</a>

            </td>

        </tr>


        <td class="bs-docs">
             <div align="center" class="<?php echo $this->alerta ?>">
                    <?php echo $this->resp ?>

                </div>
             
            <div>   
                <?php echo $this->form ?>

            </div>
           
        </td>

         <?php }else { ?>
              <tr>
            <td>
                <h4> <font color="gray">Lista de Pacientes</font></h4>

                  <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Voltar</a>


            </td>

        </tr>
        <tr>

            <td >
                <div align="center" class="<?php echo $this->alerta ?>">
                    <?php echo $this->resp ?>

                </div>

            </td>

        </tr>
       <?php } ?>
    </table>   




    <div class="busca"  >
      
        
        <table id="listar" width="100%"   class="table-hover" cellpadding="2" cellspacing="2" border="0" align="center">



            <?php if (@count($this->listaPacientes)) { ?>


                <tr class="title_tabela">
                    <th align="center">ID</th>
                    <th align="center">NOME</th>
                    <th align="center">ANIVERSÁRIO</th>
                    <th align="center">CONVÊNIO</th>
            
                </tr>
                <?php foreach ($this->listaPacientes as $paci) { ?>
                    <tr id="destaque"  data-url="<?= $this->url(array("controller" => "customer", "action" => "edit", "id" => "{$paci['paciente']}"), null, true) ?>" style="cursor: pointer" title="Clique para editar o registro">
                        <td align="center"><?php echo $paci["paciente"]; ?></td>
                        <td align="center"><?php echo $paci["name"]; ?></td>                       
                 
                        <td align="center"><?php echo $paci['birthday']; ?></td>
                        <td align="center"><?php echo $paci["convenio"]; ?></td>
                    </tr>      
                <?php } ?>
            <?php } ?>
        </table>
       
    </div>
</div>



