<?php echo $this->doctype() ?>

<head>
    <?php echo $this->headTitle('Cadastro de Paciente') ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
    <?php echo $this->headMeta() ?>

    <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery.modal.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery.formjonson.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/bootstrap.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery-ui.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery-ui-1.10.2.custom.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery.maskedinput.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/MascaraValidacao.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/converteMoeda.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/clock.js')?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/validator.js') ?>
    <?php $this->headScript()->appendFile($this->baseURL() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')) ?>


    <?php echo $this->headScript() ?>
     <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/normalize.css', 'screen') ?>
    <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/jquery-ui.css', 'screen') ?>
    <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/jquery.modal.css', 'screen') ?>
    <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/bootstrap.css', 'screen') ?>
    <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/font-awesome.css', 'screen') ?>
    <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/font-awesome-ie7.min.css', 'screen', 'IE 7') ?>

    <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/bootstrap-responsive.css', 'screen') ?>
    <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/global.css', 'screen') ?>



    <?php echo $this->headLink() ?>
    
</head>
<body>

  <!-- <script type="text/javascript">

      //  jQuery(function ($) {


         //   $("#birthday").mask("99/99/9999");

       // });

    </script>  
 -->  

    <div class="container">
        <div class="header">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>" class="brand">Cadastro de Paciente</a>
                        <div class="nav-collapse collapse">
                              <ul class="nav">
                                    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>"><i class="icon-home"></i> Início</a></li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-pencil"></i> Cadastro <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'create'), null, true) ?>">Pacientes</a></li>                                            
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-building"></i> Listar <b class="caret"></b></a>
                                        <ul class="dropdown-menu">                                            
                                            <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'listar'), null, true) ?>">Controle de Paciente</a></li>
                                        </ul>
                                </li>                           

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-calendar"></i> Data e Hora <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li> 
                                            <p align='center'>  <?php include("horas.php"); ?></p>
                                        </li>
                                    </ul>
                                </li>


                            </ul>

                            <?php
                            if (Zend_Auth::getInstance()->hasIdentity()) {
                                $identity = Zend_Auth::getInstance()->getIdentity();
                                 
                                ?>

                                <ul class="nav pull-right">
                                    <li class="dropdown">
                                        
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>                                        
                                         <?php  include("datetime.php"); echo $saudacao;
                                            echo $identity->login;
                                            ?> <b class="caret"></b></a>
                                        <form class="login-menu dropdown-menu well" action="<?= $this->url(array('controller' => 'account', 'action' => 'logout'), null, true) ?>" id="formlogout" name="formlogout">


                                            <div class="control-group">
                                                <div class="controls">
                                                    <button type="submit" class="btn btn-danger"><i class="icon-off"></i>   Encerrar Sessão</button>
                                                </div>
                                            </div>
                                            </fieldset>
                                        </form>
                                    </li>
                                </ul>
                           






        <?php } ?>
    </div><!--/.nav-collapse -->
</div><!--/.container -->
</div><!--/.navbar-inner -->
</div><!--/.navbar -->
</div>



